"""avatar

Revision ID: c8bbfc67c754
Revises: 513df1270bb6
Create Date: 2017-03-12 21:15:58.857650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bbfc67c754'
down_revision = '513df1270bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=64), nullable=True))
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
